database:
   driverClass: com.mysql.jdbc.Driver
   user: root
   password: root   
   url: jdbc:mysql://localhost:3306/hibtest
   properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQLDialect  
server:
  applicationConnectors:
  - type: http 
    port: 9000
  adminConnectors:
  - type: http
    port: 9001
    
   